repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: requirements-txt-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

    - id: ruff
      types_or: [ python, pyi, jupyter ]
